Update changelog
bigcommerce/storefront-data-hooks pull request #39
Opened 2021-03-01 16:10 UTC by jorgemasta

Add v1.1.0 to the changelog.

2021-03-02 18:25 UTC, amckemie requested changes
@jorgemasta Can you add a little more detail / clarity for the changelog items please? This will help BC set better expectations around what has changed for external devs. Thanks!

Here are specific questions I have:

1. Did any of the fixes or additions address a specific GH issue? If so, can we reference that please?
2. What was the fix for useUpdateItem?
3. What was the change for "Login SSO"?
4. Which function or hook did you add/change to allow getting products of different categories?

2021-03-03 12:24 UTC, jorgemasta commented
Thanks for the feedback @amckemie ! 🙌
I have updated the CHANGELOG

2021-03-03 16:28 UTC, amckemie approved these changes

2021-03-03 16:28 UTC, amckemie commented
@jorgemasta thanks, looks great!

2021-03-03 16:28 UTC, merged